### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by TosoxDev** [lTheon/iTheon-PDA-Taskboard#26]
There is a missing translation for the "Recover the Tracking Device" task which you can only get from Sakharov. (Short name: st_pda_caption_recover_mutant_data_location)

![yan](https://github.com/lTheon/iTheon-PDA-Taskboard/assets/57193602/4735ef9a-7ae3-4b00-b150-1253dca8f0d3)

**Comment by lTheon** [comment]
Fixed in 1.0.1
