### ISSUE TITLE
On DirectX 9 Enhanced, the "Accept task" and "Next task" buttons are invisible until you hover over them, and the textures are misplaced.

### ISSUE THREAD

**Issue by crusskittles** [lTheon/iTheon-PDA-Taskboard#28]
![Screenshot_236](https://github.com/lTheon/iTheon-PDA-Taskboard/assets/140367772/048ac8cf-f625-4ec1-b374-ea628ce090f0)
![Screenshot_231](https://github.com/lTheon/iTheon-PDA-Taskboard/assets/140367772/be049b23-9f80-498b-b5b7-039ee63ad8f5)

**Comment by crusskittles** [comment]
![Screenshot_243](https://github.com/lTheon/iTheon-PDA-Taskboard/assets/140367772/6e5933fe-1291-4294-9b5f-fee3f271c6d0)
I think it's because of the dds texture file, it can't load it properly because the bottom is missing in the dds file
Also, i think it doesn't even load the png until you hover over it on dx9

**Comment by lTheon** [comment]
Hey there
I'm afraid I won't be able to fix this issue, as it is some kind of engine quirk
It's time to upgrade your gear 😄

**Comment by crusskittles** [comment]
Damn... well thank you for taking the time to respond.

**Comment by lTheon** [comment]
@crusskittles one of Gamma players prepared his own fix for this issue by changing the icon definitions in XML. It probably breaks the icons for other DXes, so I can't add it to the base mod
https://discord.com/channels/912320241713958912/1073583008654823434/1133578983368294460
Download the archive, unpack it and place the file directly where it's located within the archive (replace the icons definition for file in the mod with it)
